name: pincer
description: "Application for controlling the Pincer robot arm"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Deals with internationalized/localized messages
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  # Package for using Google Fonts
  google_fonts: ^6.1.0
  # Provides a cross-platform (iOS, Android) API to request and check permissions
  permission_handler: ^11.1.0
  # Provides runtime functionality for playing back and interacting with animations
  # built with the Rive editor
  rive: ^0.12.4
  # Plugin for reading and writing values to local storage
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/